### ISSUE TITLE
Feature request: nested package graphs

### ISSUE THREAD

**Issue by dmontagu** [seddonym/impulse#8]
As far as I can tell, I can't inspect deeper than a single "layer" of the package at a time. Being able to generate the graph for a configurable depth (or even just manually specifying a whole list of files to look at) would be useful for determining precisely where cyclic dependencies are occurring.

**Comment by seddonym** [comment]
Thanks for the issue!

The drawgraph command does inspect deeper (it checks all the descendants of a package) but it then summarises it only at that level. So you're right, it's not possible to see just using that command.

I imagine a new command (perhaps with a text-based output) would be needed here. I wonder if you could supply some sample output to give me an example of the kind of thing you'd find it useful to see?

**Comment by dmontagu** [comment]
My problem is that when I have circular imports, and a deeply nested package structure, it’s currently very hard to figure out which files are responsible for the circular imports without pulling them up to the top level (my current workaround :). I’ll throw together a basic example and generate the graph, but the idea is:

```
package_root/
    subpackage1/
        a.py
        b.py
    subpackage2/
        c.py
        d.py
```

Let’s say a.py imports c.py and vice versa. Currently I don’t think there is any way to show that; you’d only be able to graph that subpackage1 and subpackage2 have mutual dependencies. But clearly the graph generator knows this information, I just want to see it.

**Comment by seddonym** [comment]
Ah makes sense.

One option could be to use [import-linter](https://github.com/seddonym/import-linter) which might be useful if you're trying to detect dependencies between specific packages. You'd make a contract and then it would give you a report on chains of imports break the contract.

Another option is to go lower level and use [grimp](https://github.com/seddonym/grimp/), which is a python API for interacting with your project's dependency graph.

But I guess some of that functionality could be supplied by impulse, too, in the future. In the example above, would you expect to run a general command, and it just tells you if there are any cycles within the whole package? Or would you want something more specific, eg `impulse list-cycles-between subpackage1 subpackage2`?
