### ISSUE TITLE
Feature request: bulk generation

### ISSUE THREAD

**Issue by dmontagu** [seddonym/impulse#9]
It would be nice if I could specify a package and recursively generate the single-layer graphs for all subpackages. (Currently I have to manually enter them one at a time, or at least concoct some sort cli command to accomplish this.) They could all open simultaneously, I just want to be able to review them all without running additional commands.

This is related to #8; the difference is that this would still just be a single "layer", just at multiple points.

**Comment by seddonym** [comment]
Cool idea! Something like:

```
impulse drawgraphs mypackage.foo --depth=4
```

I think there's potentially for confusion around how many graphs it would draw, maybe it would need a preview stage where it says "this will generate graphs for the following packages - are you sure?" - just to protect against someone accidentally opening hundreds of files.

I'd definitely consider a PR for this if you wanted to look at it - let me know if you would like any pointers.
